name: Deploy & Purge Cloudflare Cache

on:
  push:
    branches:
      - main

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    name: Purge Cloudflare Cache

    steps:
      - name: Purge Cloudflare Cache
        run: |
          curl -s -X POST "https://api.cloudflare.com/client/v4/zones/85acbbc7a2dbb26ec060129fab495c2f/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}' | jq .
